language: java

sudo: false
dist: trusty

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

install:
- java -version
- export GRADLE_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED -Dorg.gradle.daemon=false"
# - export GRADLE_OPTS="--permit-illegal-access"
- mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
- ./gradlew -version
- wget http://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.4.10/groovy-all-2.4.10.jar
- rm /home/travis/.gradle/wrapper/dists/gradle-3.4.1-bin/71zneekfcxxu7l9p7nr2sc65s/gradle-3.4.1/lib/groovy-all-2.4.7.jar
- cp groovy-all-2.4.10.jar /home/travis/.gradle/wrapper/dists/gradle-3.4.1-bin/71zneekfcxxu7l9p7nr2sc65s/gradle-3.4.1/lib/groovy-all-2.4.7.jar

script:
- ./gradlew --no-daemon --info --stacktrace check
